name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: check-env
        run: echo ${{ secrets.gh-actions.AWS_ACCESS_KEY_ID }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIAVP7OS4MTFAYEOPNL' 
          aws-secret-access-key: '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'
          aws-region: us-east-2
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build index.js
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=lamdba-gh-action --zip-file=fileb://deploy.zip