name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::377920611110:role/gh-actions-lambda
          aws-session-name: gh-action-session
          aws-region: us-east-2
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build index.js
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=lamdba-gh-action --zip-file=fileb://deploy.zip