name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: check-env
        run:  |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo ${{ github.actor }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAVP7OS4MTHMOFLS7O 
          aws-secret-access-key: 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
          aws-region: us-east-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build index.js
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=lamdba-gh-action --zip-file=fileb://deploy.zip